### ISSUE TITLE
cannot import name 'BlobSource' from 'azure.functions.decorators'

### ISSUE THREAD

**Issue by rahul-08-11** [Azure/azure-functions-python-worker#1567]
The azure function app is throwing an error after it is being deployed  and response 502 AND 503
![image](https://github.com/user-attachments/assets/081b4c98-09d3-4d68-8679-767d99c2fee0)

runtime version : ~4
python version : 3.9

Deployment .yml file:

```
name: Deploy Python project to Azure Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'function'   ## my function name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       
  PYTHON_VERSION: '3.9'                     

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest --disable-warnings

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} 
        scm-do-build-during-deployment: true
        enable-oryx-build: true
```

```shell
azure-functions==1.20.0
pydantic==2.8.2
pydantic_core==2.20.1
pytest==8.3.2
pytest-asyncio==0.23.8
requests==2.32.3
```
