### ISSUE TITLE
Provide Travis script for deployment

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#182]
If the function app requires a package that does not offer manylinux wheels on PyPI, the user should be able to sign up for a Linux based CI system (such as Travis) to build their final deployment package. 

We need to recommend an example script for this purpose.

**Comment by asavaritayal** [comment]
```yml
sudo: required

language: generic

services:
  - docker

before_install:
- docker pull microsoft/azure-functions-python3.6
- docker run -it -v /home/travis/build/<guthub username>/<repo name>:/home/site/wwwroot:rw microsoft/azure-functions-python3.6  /bin/sh -c "cd /home/site/wwwroot; python -m venv --copies worker_venv; source worker_venv/bin/activate; pip install -r requirements.txt; apt-get update; apt-get install zip -y; zip --symlinks -r /home/site/wwwroot/app.zip .;"

- echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
- curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
- sudo apt-get install apt-transport-https
- sudo apt-get update && sudo apt-get install azure-cli

script:
- ls

deploy:
  provider: script
  script:
  - az login -u <username> -p <password>
  - az functionapp deployment source config-zip -g <myRG> -n <myAppName> --src app.zip
  on:
    branch: master
```

**Comment by asavaritayal** [comment]
@ahmelsayed can you please review the logic above? Let me know if I missed anything and/or if there is room for optimization.

**Comment by ahmelsayed** [comment]
The script looks good to me overall. [`/home/site/wwwroot/worker_venv`](https://github.com/Azure/azure-functions-docker/blob/3f97e15c921750b50dbe9fdc7fa8383c576eb841/host/2.0/stretch/amd64/python3.6/start.sh#L14-L18) is the right location for a custom venv.

 One comment, change the image from `docker pull microsoft/azure-functions-python3.6` to `docker pull mcr.microsoft.com/azure-functions/python:2.0`

also you have a small typo `guthub` -> `github`

**Comment by asavaritayal** [comment]
Awesome, thanks for reviewing! I just updated the script with respect to your comments above. Will go ahead and include this in the docs.

**Comment by asavaritayal** [comment]
Quick update on this - The `app.zip` gets built as expected but publishing doesn't quite work. Keeping the issue open since this will need some further investigation. 

/cc @ahmelsayed @davidebbo

**Comment by ahmelsayed** [comment]
Here is a travis script that works for my repo https://github.com/ahmelsayed/python-functions 

```yml
sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

before_install:
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get install -y apt-transport-https
  - sudo apt-get update && sudo apt-get install -y azure-cli
  - npm i -g azure-functions-core-tools --unsafe-perm true


script:
  - az login --service-principal --username "$APP_ID" --password "$PASSWORD" --tenant "$TENANT_ID"
  - az account get-access-token --query "accessToken" | func azure functionapp publish $APP_NAME --build-native-deps
```
