### ISSUE TITLE
Azure Pipelines zip deployment not working

### ISSUE THREAD

**Issue by jeffthink** [Azure/azure-functions-python-worker#590]
#### Investigative information

- Timestamp: 2019-12-05 8:31pm EST
- Python 3.7.4

#### Repro steps

1. Write function app using new organizational structure of `__app__` and `tests` at top level.
2. Create Function app successfully `az functionapp create --resource-group {myResourceGroup} --os-type Linux --consumption-plan-location westus  --runtime python --runtime-version 3.7 --name {myFunctionAppName} --storage-account {myStorageAccount}`
2. Deploy Function app successfully the first time from local computer: `cd __app__; func azure functionapp publish {myFunctionAppName} --build remote --publish-local-settings`
3. Create Azure Devops Pipeline starting from base Azure Functions template and tweak it so that it looks like the `not-working-azure-pipelines.yaml` file from this gist: https://gist.github.com/jeffthink/f712444c63da578e0f7f07a765e2c581

#### Expected behavior

Function app should deploy successfully and be able to triggered so that the python code in `__init__.py` can leverage modules that are specified in `requirements.txt`

#### Actual behavior

* Function app deploys successfully using this CI process (i.e. no errors).
* Run function app (either from Function App UI, or by hitting function url), and get 500 error saying that "Module X could not be found".  This shows up regardless of which modules I include/don't include, suggesting that the deployed function app can't find any modules in requirements.txt.
* I have verified that the deployed zip file shows up correctly in the `WEBSITE_RUN_FROM_PACKAGE` env variable and that when downloaded, it contains the requirements folders (I've tried naming this folder `worker_env`, `.python_packages`, `.venv`, etc.).

#### Known workarounds

If I deploy the function using core-tools as part of the devops pipeline (as seen in the `is-working-azure-pipelines.yaml` file in https://gist.github.com/jeffthink/f712444c63da578e0f7f07a765e2c581 gist), the function app deploys successfully and can be triggered without an error.

#### Related information 

I tried a variety of iterations of virtual env names, parameters in the deployment step, etc., all to no avail.

Thanks for the help!

```txt
azure-functions==1.0.5
azure-storage-blob==2.1.0
stitchclient==0.6.0
pandas==0.25.2
requests==2.12.4
bs4==0.0.1
python-dateutil==2.6.1
```

![image](https://user-images.githubusercontent.com/131977/70289144-dc373300-17a1-11ea-92a6-995e59ad904c.png)

**Comment by Hazhzeng** [comment]
Hi @jeffthink,

Thanks for reporting this issue and sorry for the late reply.
This is due to an outdated version of Azure DevOps pipeline template in https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-azure-devops

We no longer support worker_venv in Python 3.7, instead, we will use the **./.python_packages/lib/site-packages** folder to store the Python modules
```yaml
- task: UsePythonVersion@0
  displayName: "Setting python version to 3.7 as required by functions"
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'
- bash: |
    if [ -f extensions.csproj ]
    then
        dotnet build extensions.csproj --output ./bin
    fi
    pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
```
I've raised an issue and the new doc will soon be available.
