### ISSUE TITLE
ModuleNotFoundError when using DevOps Pipeline Task AzureFunctionApp@1

### ISSUE THREAD

**Issue by Fl4v** [Azure/azure-functions-python-worker#708]
### Investigative information

When deploying my function from a DevOps pipeline, using the **AzureFunctionApp@1** task, the python worker is unable to find the correct modules.

As a default, the above tasks will upload your `.zip` function code to the Function's storage account, and the following App Setting added: **WEBSITE_RUN_FROM_PACKAGE**, where the value is the path to the blob item.

I have tried troubleshooting this error as described by this [page](https://docs.microsoft.com/en-us/azure/azure-functions/recover-module-not-found?tabs=manual). The documentation indicates that when having troubles with python modules, the following should be added to the application's settings: **SCM_DO_BUILD_DURING_DEPLOYMENT** and **ENABLE_ORYX_BUILD**.

However, when using **WEBSITE_RUN_FROM_PACKAGE**, which is the default behavior of **AzureFunctionApp@1**, **SCM_DO_BUILD_DURING_DEPLOYMENT** is actually ignored. This is documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package).

### Repro steps

Using the DevOps Pipeline builder, build your pipeline following the UI. At the end of the process, you should have a pipeline that should look similar to the below. Alternatively, you can use this [template ](https://github.com/microsoft/azure-pipelines-yaml/blob/master/templates/python-functionapp-to-linux-on-azure.yml) from Microsoft as a guideline.

```yml
trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '{{some_subscription}}'

  # Function app name
  functionAppName: '{{some_function}}'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/functions'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - bash: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
        fi
      workingDirectory: $(workingDirectory)
      displayName: 'Build extensions'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.7'
      inputs:
        versionSpec: 3.7 # Functions V2 supports Python 3.6 as of today

    - bash: |
        python -m venv worker_venv
        source worker_venv/bin/activate
        pip install -r requirements.txt
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
```

### Expected behavior

I expect that my function will find and install all the python libraries stored in the `requirements.txt` file in the project directory during or after deployment.

### Actual behavior

Python worker is unable to find any modules that my function needs.

### Known workarounds

Deploy your function using the VSCode Function extension.

### Contents of the requirements.txt file:

```txt
azure-functions==1.2.1
azure-storage-blob==12.3.1
flake8==3.8.1
beautifulsoup4==4.9.1
pytest==5.4.2
sendgrid==6.3.1
```
