### ISSUE TITLE
How to properly install python modules with venv using DevOps Pipeline build? Module Not Found Error

### ISSUE THREAD

**Issue by georghildebrand** [Azure/azure-functions-python-worker#727]
**Note:** There are already several issues mentioning this problem, but several of these were closed after finding some quickfix which were not working for me. See i.e. this [issue](https://github.com/Azure/azure-functions-python-worker/issues/627).

**Issue Statement:**
The general problem is that it seems not to be possible for me to import packages installed during DevOps pipline in an app. In my case i want to use `azure.servicebus` and have to use the SDK as the bindings don't fullfill my requirements. 
However, after building with devops and uploading the artifact via `SCM_RUN_FROM_PACKAGE` the app starts running, but is not able to import the module from neither `worker_env` nor from `.python_packages...` 

When deploying from local via function app core tools the problem does not occur. However, for deploying to production I have to use DevOps pipline!

###### Please provide the following:

- Timestamp: 2020-07-15
- Function App name: functestkjskdj
- Core Tools version: 3.0.2534

###### Provide the steps required to reproduce the problem:

I use the following YAML in my Azure Pipelines Build:

```
trigger:
  - master
  - dev-*

variables:

  functionAppName: '$(FUNCTION_APP_NAME)'
  azureSubscription: '$(SERVICE_CONNECTION_NAME)'
  storageName: '$(FUCTION_APP_STORAGE_ACCOUNT_NAME)'
  resourceGroupName: '$(FUNCTION_APP_RESOURCE_GROUP_NAME)'

pool:
  vmImage: ubuntu-18.04
steps:
- task: UsePythonVersion@0
  displayName: "Setting python version to 3.6 as required by functions"
  inputs:
    versionSpec: '3.6' # Change Python version if necessary
    architecture: 'x64'
- script: |
    # dotnet restore # COMMENT OUT IF NOT USING FUNCTION EXTENSIONS
    # dotnet build --output './bin/' # COMMENT OUT IF NOT USING FUNCTION EXTENSIONS
    #source $(workingDirectory)/worker_venv/bin/activate
    #pip install -r requirements.txt
    #worker_venv/lib/python3.6/site-packages
    #pip install --target="$(workingDirectory)/.python_packages/lib/site-packages" -r requirements.txt
    pip install --target="worker_venv/lib/python3.6/site-packages" -r requirements.txt

- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureFunctionApp@1
  displayName: "Azure functions app deploy"
  inputs:
    # todo: make service connection dynamic for alpha,beta,ga
    azureSubscription: $(azureSubscription) # here the subscription or service connection name
    appType: functionAppLinux
    appName: $(functionAppName)
    packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'

```

###### Provide a description of the expected behavior.

After deployment i would expect that I can import the modules from `requirements.txt`  from my function modules.

###### Provide a description of the actual behavior observed.

Imports of modules from `requirements.txt`  produce **Module Not Found Error**

###### Provide a description of any known workarounds.

I was not finding any workaround except doing zip deploy via core tools which is not really usable when using CI/CD via DevOps.

###### Provide the requirements.txt file to help us find out module related issues.

```
azure-servicebus
numpy
```

###### Provide any related information

I shared the testapp i am using on github: https://github.com/georghildebrand/functestkjskdj
Note that i am not breaking on import error. Instead i string the errors and output it at REST. I am doing this as the monitoring is very slow which makes debugging at higher iteration speed very hard. 

<!-- Uncomment this if you want to include your source (wrap it in details to make browsing easier)
<details>
<summary>Source</summary>

**Comment by TobiahZ** [comment]
We just ran into this same issue.

Changing `pip install -r requirements.txt` in the YAML file to `pip install --target="$(workingDirectory)/.python_packages/lib/site-packages" -r requirements.txt` resolved it for us.

We definitely would expect to not have to specify the target in order for `pip install -r requirements.txt` to be deployed.

**Comment by TobiahZ** [comment]
Here is our working YAML for installing dependencies that is working for us.

```
    - bash: |
        python -m venv worker_venv
        source worker_venv/bin/activate
        pip install --target="$(workingDirectory)/.python_packages/lib/site-packages" -r requirements.txt
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'
```

Perhaps you need to define workingDirectory?

**Comment by georghildebrand** [comment]
> We just ran into this same issue.
> 
> Changing `pip install -r requirements.txt` in the YAML file to `pip install --target="$(workingDirectory)/.python_packages/lib/site-packages" -r requirements.txt` resolved it for us.
> 
> We definitely would expect to not have to specify the target in order for `pip install -r requirements.txt` to be deployed.

Thanks @TobiahZ , that was not effective on my side. I tried all the tips from the other thread already.

**Comment by georghildebrand** [comment]
> Here is our working YAML for installing dependencies that is working for us.
> 
> ```
>     - bash: |
>         python -m venv worker_venv
>         source worker_venv/bin/activate
>         pip install --target="$(workingDirectory)/.python_packages/lib/site-packages" -r requirements.txt
>       workingDirectory: $(workingDirectory)
>       displayName: 'Install application dependencies'
> ```
> 
> Perhaps you need to define workingDirectory as '$(System.DefaultWorkingDirectory)/'?


Tried the idea, but it produces the following error in my setup: 

`##[error]Not found workingDirectory: /home/vsts/work/1/s/$(workingDirectory)`

**Comment by georghildebrand** [comment]
> Here is our working YAML for installing dependencies that is working for us.
> 
> ```
>     - bash: |
>         python -m venv worker_venv
>         source worker_venv/bin/activate
>         pip install --target="$(workingDirectory)/.python_packages/lib/site-packages" -r requirements.txt
>       workingDirectory: $(workingDirectory)
>       displayName: 'Install application dependencies'
> ```
> 
> Perhaps you need to define workingDirectory as '$(System.DefaultWorkingDirectory)/'?

Gave it a quick try, but its also not resolving my issue. The package builds and everything looks fine but when calling the HTTP Trigger it still reports : Module not found ... I think i will switch to docker based function now

**Comment by georghildebrand** [comment]
So with some help from the azure fast track team i found out how to run it. But it feels pretty much confusing:

This is what we did:

- we setted the variable: `workingDirectory: '$(Build.SourcesDirectory)'`
- replaced: archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
- then it was still not working
- so we created a new app container: functestnewtry
- deployed to that one - worked.

Don't ask my why or how... seems to be some black magic or interceptions with the directory structures. Maybe someone from functions team can clear it up. However, the below code works for me now on a fresh made app function in azure!!!

```
trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '<serviceconnection here>'

  # Function app name
  functionAppName: 'functestnewtry'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Working Directory
  workingDirectory: '$(Build.SourcesDirectory)'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - bash: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
        fi
      workingDirectory: $(workingDirectory)
      displayName: 'Build extensions'
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6

    - bash: |
        python -m venv worker_venv
        source worker_venv/bin/activate
        pip install -r requirements.txt
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
```
