### ISSUE TITLE
Python Azure function can't load pyodbc under Linux

### ISSUE THREAD

**Issue by Avalaxy** [Azure/azure-functions-python-worker#827]
I built an Azure function in Python that I'm deploying to a Linux function app (consumption type). I use the standard Azure Devops pipeline to deploy the function. However, when I run the function it gives me this error:

```
Result: Failure Exception: ModuleNotFoundError: No module named 'pyodbc'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound Stack: File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 284, in _handle__function_load_request func = loader.load_function( File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 42, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/loader.py", line 76, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/site/wwwroot/RecreateStoredProcedure/__init__.py", line 2, in <module> import pyodbc
```

My function (simplified) looks like this:
```
import logging
import pyodbc
import azure.functions as func

username = "username"
password = "password"

driver = '{ODBC Driver 17 for SQL Server}'

def main(req: func.HttpRequest) -> func.HttpResponse:
    databaseName = req.params.get('databaseName')

    if (not databaseName):
        serverPath = 'asdasdasd.database.windows.net'

        con = pyodbc.connect('Driver={SQL Server};'
                        'Server='+serverPath+';'
                        'Database='+databaseName+';'
                        'UID='+username+';'
                        'PWD='+password

        return func.HttpResponse(f"Successful.")
    else:
        return func.HttpResponse("Error.",status_code=500)
```

The requirements.txt file looks like this:
```
azure-functions
pyodbc==4.0.30
```

Finally, my devops pipeline looks like this (again, it's built using the default Azure Function Python template):

```
stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - bash: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
        fi
      workingDirectory: $(workingDirectory)
      displayName: 'Build extensions'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.9'
      inputs:
        versionSpec: 3.9 # Functions V2 supports Python 3.6 as of today

    - bash: |
        python -m venv worker_venv
        source worker_venv/bin/activate
        pip install -r requirements.txt
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
```

I tried the following things:

- Creating a Windows function app instead (not possible, it's greyed out)
- Trying it with Docker (not possible, consumption plan is not available for Docker for whatever reason)
- I tried pypyodbc (not working locally, so not a solution)
- I created a separate release pipeline where I tried this: https://clemenssiebler.com/deploy-azure-functions-python-azure-devops/ (this also doesn't work, there is an unspecified error while trying to install Function tools: Script failed with exit code: 127)

It's super weird, creating a Python function that runs on Linux and connects with a database is a super super standard scenario I would say. Why does this not work out of the box? How can I solve this?

**Comment by Avalaxy** [comment]
@Hazhzeng @vrdmr do you know when I can expect to get a response on this issue? I need to know what my prospect are and if I should ditch Azure Functions or not.

**Comment by stefanushinardi** [comment]
Hello @Avalaxy , I am taking a look at this issue. Thanks for your patience.

**Comment by stefanushinardi** [comment]
Hi @Avalaxy, I realized that the template might be outdated. I verified on my side that I was able to import pyodbc. Could you give this template ago?

```yaml

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 

  # Function app name
  functionAppName: 

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-18.04

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.9'
      inputs:
        versionSpec: 3.9 # Functions V2 supports Python 3.6 as of today
        architecture: 'x64'
    - bash: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --output ./bin
        fi
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
      workingDirectory: $(workingDirectory)

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: ubuntu-18.04
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
```
cc: @Hazhzeng @vrdmr
